### ISSUE TITLE
feat: npmパッケージのバージョンを固定してインストールさせたい

### ISSUE THREAD

**Issue by cle-uv** [cle-uv/create-react-app#24]
~~npmパッケージのバージョン固定のためにnpmrcを追加します。~~

yarnなのでyarnrcを利用し、save-prefix設定を追加します。

**Comment by piro0919** [comment]
@cle-uv 
.npmrcが動作するのはnpm環境のみですね
yarn環境では動かないため、他の対処が必要です

**Comment by piro0919** [comment]
@cle-uv 
issueのタイトルも的確でないですね
「バージョンを固定してnpmパッケージをインストールしたい」とか、そんな感じのニュアンスにしないと毎回立て直すことになってしまいます 🙅‍♂️

**Comment by cle-uv** [comment]
@piro0919 
issueタイトルを修正しました！
タイトルを見て内容分かるようにしていきます 💪
