### ISSUE TITLE
sassの導入

### ISSUE THREAD

**Issue by cle-uv** [cle-uv/create-react-app#3]
css-modules × sassで行きます。

**Comment by piro0919** [comment]
@cle-uv 一応その組み合わせを選んだ理由をお願いしますー 🙇

**Comment by cle-uv** [comment]
@piro0919 
まずはcreate-react-app公式docにあるものに近い状態で覚えていこうと思いそうしました。
とはいえコードが綺麗になりそうなbabel-plugin-react-css-modulesを入れようかも悩んでおります。
一旦babel-plugin-react-css-modulesも使ってみて、導入するかちゃんと検討したほうが良かったですね。反省。

**Comment by piro0919** [comment]
@cle-uv 
今回はcss modules × sassでいきましょう 👍
