### ISSUE TITLE
feat:cssリセットを追加

### ISSUE THREAD

**Issue by cle-uv** [cle-uv/create-react-app#4]
postcss-normalizeを利用してcssリセットします。

**Comment by piro0919** [comment]
@cle-uv 
選定理由をお願いしますー 👍

**Comment by cle-uv** [comment]
@piro0919 
こちら公式の通りに入れたものになります。デフォルトで使えるものだったので！
https://create-react-app.dev/docs/adding-css-reset

**Comment by piro0919** [comment]
@cle-uv 
goodです 👍
